### PR TITLE
FIX: issue #29

### PR DESCRIPTION
**Pull request by shamindras**
Include travis.yml file, include requirements.txt and test requirements
add in coveralls

### CODE REVIEW

**Comment by shamindras** [comment]
Tried to follow the [following simple example](https://github.com/domenkozar/nose-selecttests/blob/master/.travis.yml)

**Comment by stefanv** [comment]
That looks fine, although I'd probably use pytest instead of nose now.  Switch on Travis and see how it goes!

**Comment by shamindras** [comment]
Thanks @stefanv . I used `nose` instead of `pytest` as [`scikit-learn` currently uses `nose`](https://github.com/scikit-learn/scikit-learn/blob/master/build_tools/appveyor/requirements.txt). I thought this would make it easier to write and integrate our code/ tests into the `scikit-learn` fork later.

Should we switch to pytest still?

**Comment by stefanv** [comment]
Oh, I see. I thought they'd have switched by now! Yes, it's really no big 
deal. More important to have Travis up and running!

**Comment by shamindras** [comment]
@stefanv - travis now working. Are you happy to merge. This commit also includes the RIT code from today in the form of a notebook. I'll convert to a python module in another issue/ PR

**Comment by shamindras** [comment]
close #29

**Pull request merged**
